# -*- coding: utf-8 -*-
"""BNN Bit Packed FPGA Export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNGzMx-4uazkAEhAMdJPLb_c4mRhVD4U
"""

#!/usr/bin/env python3
# train_xnor_bnn_bitpacked_fpga.py
# XNOR-style BNN training (STE) + bitpacked weight export for FPGA (no ESP32 / runtime accuracy)

import numpy as np
from tensorflow.keras.datasets import mnist
import time
import os

np.random.seed(0)

# ---------------- CONFIG ----------------
INPUT = 784
HIDDEN = 1024
OUTPUT = 10

LR = 5e-3
BATCH = 256
EPOCHS = 30
SAVE_PATH = "bnn_trained_model_xnor.npz"

WORDS_INPUT = (INPUT + 31) // 32
WORDS_HIDDEN = (HIDDEN + 31) // 32
# ----------------------------------------


# ---------------- utils -----------------
def one_hot(y, n=10):
    t = np.zeros((y.size, n), dtype=np.float32)
    t[np.arange(y.size), y] = 1.0
    return t

def softmax(x):
    ex = np.exp(x - np.max(x, axis=1, keepdims=True))
    return ex / np.sum(ex, axis=1, keepdims=True)

def cross_entropy(p, y):
    eps = 1e-9
    return -np.mean(np.sum(y * np.log(p + eps), axis=1))

def popcount32_np(arr):
    try:
        return arr.view(np.uint32).bit_count()
    except Exception:
        v = np.array([int(x).bit_count() for x in arr.ravel()], dtype=np.int32)
        return v.reshape(arr.shape)

def pack_bits_row(bits):
    L = len(bits)
    words = (L + 31)//32
    out = np.zeros(words, dtype=np.uint32)
    for i in range(words):
        chunk = bits[i*32:(i+1)*32]
        val = 0
        for j, b in enumerate(chunk):
            if int(b):
                val |= (1 << j)
        out[i] = np.uint32(val)
    return out

def pack_bits_matrix(binmat):
    rows, cols = binmat.shape
    words = (cols + 31) // 32
    out = np.zeros((rows, words), dtype=np.uint32)
    for r in range(rows):
        out[r] = pack_bits_row(binmat[r])
    return out

def binarize_x(x, thresh=0.25):
    return (x > thresh).astype(np.uint8)

# ---------------------------------------


# --------------- data -------------------
print("Loading MNIST...")
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, INPUT).astype(np.float32) / 255.0
x_test  = x_test.reshape(-1, INPUT).astype(np.float32) / 255.0
y_train_oh = one_hot(y_train, OUTPUT)
y_test_oh  = one_hot(y_test, OUTPUT)

# train / val split
x_tr = x_train[:50000]; y_tr = y_train_oh[:50000]
x_val = x_train[50000:60000]; y_val = y_train_oh[50000:60000]
# ----------------------------------------


# --------------- model ------------------
class XNOR_BNN_Model:
    def __init__(self, input_dim, hidden, out, lr=1e-3):
        self.inp = input_dim
        self.h = hidden
        self.out = out

        self.w1 = np.random.randn(self.inp, self.h).astype(np.float32) * 0.05
        self.b1 = np.zeros((1, self.h), dtype=np.float32)
        self.w2 = np.random.randn(self.h, self.out).astype(np.float32) * 0.05
        self.b2 = np.zeros((1, self.out), dtype=np.float32)

        # simple BN parameters
        self.gamma1 = np.ones((1, self.h), dtype=np.float32)
        self.beta1  = np.zeros((1, self.h), dtype=np.float32)
        self.gamma2 = np.ones((1, self.out), dtype=np.float32)
        self.beta2  = np.zeros((1, self.out), dtype=np.float32)

        self.lr = lr

        # Adam state
        self.adam_state = {}
        for name, p in [("w1", self.w1), ("b1", self.b1),
                        ("w2", self.w2), ("b2", self.b2),
                        ("g1", self.gamma1), ("bta1", self.beta1),
                        ("g2", self.gamma2), ("bta2", self.beta2)]:
            self.adam_state[name] = {"m": np.zeros_like(p), "v": np.zeros_like(p), "t": 0}

    def adam_step(self, name, param, grad, lr=None):
        if lr is None:
            lr = self.lr
        s = self.adam_state[name]
        b1, b2 = 0.9, 0.999
        eps = 1e-8
        s["t"] += 1
        s["m"] = b1 * s["m"] + (1 - b1) * grad
        s["v"] = b2 * s["v"] + (1 - b2) * (grad * grad)
        mhat = s["m"] / (1 - b1 ** s["t"])
        vhat = s["v"] / (1 - b2 ** s["t"])
        step = lr * mhat / (np.sqrt(vhat) + eps)
        param -= step
        return param

    def binary_weight_float(self, alpha=1.0):
        w1_sign = np.sign(self.w1)
        w1_sign[w1_sign == 0] = 1.0
        w2_sign = np.sign(self.w2)
        w2_sign[w2_sign == 0] = 1.0

        scale1 = np.mean(np.abs(self.w1), axis=0, keepdims=True) + 1e-12
        scale2 = np.mean(np.abs(self.w2), axis=0, keepdims=True) + 1e-12

        w1_b = w1_sign * scale1
        w2_b = w2_sign * scale2
        return w1_b.astype(np.float32), w2_b.astype(np.float32)

    def forward_float(self, X, alpha=1.0):
        w1_b, w2_b = self.binary_weight_float(alpha)
        z1 = X.dot(w1_b) + self.b1
        mu1 = np.mean(z1, axis=0, keepdims=True)
        std1 = np.std(z1, axis=0, keepdims=True) + 1e-5
        x1 = (z1 - mu1) / std1
        z1a = self.gamma1 * x1 + self.beta1
        a1 = np.clip(z1a, -1.0, 1.0)

        z2 = a1.dot(w2_b) + self.b2
        mu2 = np.mean(z2, axis=0, keepdims=True)
        std2 = np.std(z2, axis=0, keepdims=True) + 1e-5
        x2 = (z2 - mu2) / std2
        z2a = self.gamma2 * x2 + self.beta2
        out = softmax(z2a)
        return out, (w1_b, w2_b, z1, x1, z1a, a1, z2, x2, z2a)

    def backward_and_update(self, X, y, internals, lr=None):
        out, (w1_b, w2_b, z1, x1, z1a, a1, z2, x2, z2a) = internals
        if lr is None:
            lr = self.lr
        m = X.shape[0]

        # output
        dz2a = (out - y) / m
        dgamma2 = np.sum(dz2a * x2, axis=0, keepdims=True)
        dbeta2  = np.sum(dz2a, axis=0, keepdims=True)
        dz2 = dz2a * self.gamma2
        dw2_b = a1.T.dot(dz2)
        db2   = np.sum(dz2, axis=0, keepdims=True)

        # hidden
        da1 = dz2.dot(w2_b.T)
        dact = (np.abs(z1a) <= 1.0).astype(np.float32)
        dz1a = da1 * dact

        dgamma1 = np.sum(dz1a * x1, axis=0, keepdims=True)
        dbeta1  = np.sum(dz1a, axis=0, keepdims=True)
        dz1 = dz1a * self.gamma1
        dw1_b = X.T.dot(dz1)
        db1   = np.sum(dz1, axis=0, keepdims=True)

        # STE for real weights
        ste_mask_w1 = (np.abs(self.w1) <= 1.0).astype(np.float32)
        ste_mask_w2 = (np.abs(self.w2) <= 1.0).astype(np.float32)
        dw1 = dw1_b * ste_mask_w1
        dw2 = dw2_b * ste_mask_w2

        # gradient clipping
        maxg = 5.0
        dw1 = np.clip(dw1, -maxg, maxg)
        dw2 = np.clip(dw2, -maxg, maxg)
        db1 = np.clip(db1, -maxg, maxg)
        db2 = np.clip(db2, -maxg, maxg)

        # adam updates
        self.w1 = self.adam_step("w1", self.w1, dw1, lr)
        self.b1 = self.adam_step("b1", self.b1, db1, lr)
        self.w2 = self.adam_step("w2", self.w2, dw2, lr)
        self.b2 = self.adam_step("b2", self.b2, db2, lr)
        self.gamma1 = self.adam_step("g1", self.gamma1, dgamma1, lr)
        self.beta1  = self.adam_step("bta1", self.beta1, dbeta1, lr)
        self.gamma2 = self.adam_step("g2", self.gamma2, dgamma2, lr)
        self.beta2  = self.adam_step("bta2", self.beta2, dbeta2, lr)

        # keep real weights in [-1,1]
        self.w1 = np.clip(self.w1, -1.0, 1.0)
        self.w2 = np.clip(self.w2, -1.0, 1.0)

    # ---------- bitpacked conversion for FPGA ----------
    def build_bitpacked(self, calib_samples=6000):
        """
        Build bitpacked weights + calibrated thresholds TH1 (hidden) and TH2 (output)
        using the validation set. These are what you will use in FPGA.
        """

        # 1) PACK WEIGHTS (±1 -> {0,1} bits -> uint32 words)

        # W1: [INPUT, HIDDEN] -> bits [HIDDEN, INPUT] -> packed [HIDDEN, WORDS_INPUT]
        w1_sign = np.sign(self.w1)
        w1_sign[w1_sign == 0] = 1.0
        w1_bits = ((w1_sign.T + 1.0) / 2.0).astype(np.uint8)
        W1_packed = pack_bits_matrix(w1_bits)

        # W2: [HIDDEN, OUTPUT] -> bits [OUTPUT, HIDDEN] -> packed [OUTPUT, WORDS_HIDDEN]
        w2_sign = np.sign(self.w2)
        w2_sign[w2_sign == 0] = 1.0
        w2_bits = ((w2_sign.T + 1.0) / 2.0).astype(np.uint8)
        W2_packed = pack_bits_matrix(w2_bits)

        # 2) CALIBRATION DATA (from global x_val / y_val)
        global x_val, y_val
        n_cal = min(calib_samples, x_val.shape[0])
        Xcal = x_val[:n_cal]
        Ycal_oh = y_val[:n_cal]
        Ycal_labels = np.argmax(Ycal_oh, axis=1)

        # 3) FLOAT HIDDEN ACTIVATION SIGN AS TARGET FOR TH1
        _, internals = self.forward_float(Xcal)
        a1_float = internals[5]                      # shape [n_cal, HIDDEN]
        hidden_target = (a1_float > 0).astype(np.uint8)  # [n_cal, HIDDEN]

        # 4) BINARIZE INPUTS & PACK (MUST MATCH FPGA INPUT BINARIZATION)
        n_words_input = (self.inp + 31) // 32
        inputs_packed = np.zeros((n_cal, n_words_input), dtype=np.uint32)
        for i in range(n_cal):
            b = (Xcal[i] > 0.25).astype(np.uint8)    # same threshold as binarize_x
            inputs_packed[i] = pack_bits_row(b)

        # 5) CALIBRATE TH1 + BUILD PACKED HIDDEN LAYER FOR CAL SAMPLES
        H = self.h
        TH1 = np.zeros(H, dtype=np.int32)

        n_words_hidden = (H + 31) // 32
        hidden_packed_cal = np.zeros((n_cal, n_words_hidden), dtype=np.uint32)

        for h in range(H):
            wwords = W1_packed[h]  # [WORDS_INPUT]

            xor = np.bitwise_xor(inputs_packed, wwords)
            xnor = np.bitwise_not(xor).astype(np.uint32)
            pc = np.sum(popcount32_np(xnor), axis=1)  # [n_cal]

            target = hidden_target[:, h]
            candidates = np.unique(pc)

            best_acc = -1
            best_T = int(self.inp // 2)
            for T in candidates:
                pred = (pc >= T).astype(np.uint8)
                acc = (pred == target).sum()
                if acc > best_acc:
                    best_acc = acc
                    best_T = int(T)

            TH1[h] = best_T

            # pack hidden bits for this neuron
            pred_final = (pc >= TH1[h]).astype(np.uint8)  # [n_cal]
            word_idx = h // 32
            bit_off = h % 32
            mask_vec = (pred_final.astype(np.uint32) << bit_off)
            hidden_packed_cal[:, word_idx] |= mask_vec

        # 6) CALIBRATE TH2 USING CLASS LABELS
        O = self.out
        TH2 = np.zeros(O, dtype=np.int32)

        # score2[o, i] = 2*popcount(XNOR(hidden_bits_i, W2[o])) - H
        score2 = np.zeros((O, n_cal), dtype=np.int32)

        for o in range(O):
            wwords2 = W2_packed[o]  # [WORDS_HIDDEN]
            xor2 = np.bitwise_xor(hidden_packed_cal, wwords2)
            xnor2 = np.bitwise_not(xor2).astype(np.uint32)
            pc2 = np.sum(popcount32_np(xnor2), axis=1)  # [n_cal]
            s2 = 2 * pc2 - H
            score2[o, :] = s2

        for o in range(O):
            mask = (Ycal_labels == o)
            if np.any(mask):
                TH2[o] = int(np.median(score2[o, mask]))
            else:
                TH2[o] = int(np.median(score2[o, :]))

        # store for later use (if needed)
        self.W1_packed = W1_packed
        self.W2_packed = W2_packed
        self.TH1 = TH1
        self.TH2 = TH2

        return W1_packed, W2_packed, TH1, TH2

    def update_bitpacked_from_current(self):
        self.W1_packed, self.W2_packed, self.TH1, self.TH2 = self.build_bitpacked()

    def save_npz(self, path):
        np.savez_compressed(
            path,
            w1=self.w1, b1=self.b1,
            w2=self.w2, b2=self.b2,
            gamma1=self.gamma1, beta1=self.beta1,
            gamma2=self.gamma2, beta2=self.beta2
        )

# ----------------------------------------


# --------------- TRAINING --------------------
model = XNOR_BNN_Model(INPUT, HIDDEN, OUTPUT, lr=LR)
print("Model initialized:", INPUT, HIDDEN, OUTPUT)

best_val = 0.0
best_state = None

for epoch in range(1, EPOCHS + 1):

    # LR decay
    if epoch == 60:
        model.lr = 5e-4
        print("LR decayed -> 5e-4")
    if epoch == 120:
        model.lr = 1e-4
        print("LR decayed -> 1e-4")

    t0 = time.time()
    idx = np.random.permutation(x_tr.shape[0])
    x_tr = x_tr[idx]; y_tr = y_tr[idx]

    # mini-batch training
    for i in range(0, x_tr.shape[0], BATCH):
        xb = x_tr[i:i+BATCH]
        yb = y_tr[i:i+BATCH]
        out, internals = model.forward_float(xb)
        model.backward_and_update(xb, yb, (out, internals))

    # validation accuracy (for monitoring only, not used in FPGA)
    pv, _ = model.forward_float(x_val)
    val_acc = np.mean(np.argmax(pv, axis=1) == np.argmax(y_val, axis=1))
    t1 = time.time()

    print(f"Epoch {epoch:03d}/{EPOCHS}  val_acc={val_acc*100:.2f}%  time={t1-t0:.1f}s")

    if val_acc > best_val:
        best_val = val_acc
        best_state = (
            model.w1.copy(), model.b1.copy(),
            model.w2.copy(), model.b2.copy(),
            model.gamma1.copy(), model.beta1.copy(),
            model.gamma2.copy(), model.beta2.copy()
        )

# restore best validation state
if best_state is not None:
    (model.w1, model.b1, model.w2, model.b2,
     model.gamma1, model.beta1, model.gamma2, model.beta2) = best_state

# (Optional) Save float model params
model.save_npz(SAVE_PATH)
print("Saved float BNN parameters to", SAVE_PATH)

# ------- BUILD BITPACKED WEIGHTS & THRESHOLDS FOR FPGA -------
print("Building bitpacked weights + thresholds for FPGA...")
W1_packed, W2_packed, TH1, TH2 = model.build_bitpacked()
print("Bitpacked shapes:")
print("  W1_packed:", W1_packed.shape)  # (HIDDEN, WORDS_INPUT)
print("  W2_packed:", W2_packed.shape)  # (OUTPUT, WORDS_HIDDEN)


# ------- EXPORT TO HEX FILES FOR FPGA ROMS -------

def save_hex_matrix(filename, mat):
    """
    Save 2D uint32 matrix as HEX lines.
    Each line is one 32-bit word in big-endian hex (8 chars).
    """
    with open(filename, "w") as f:
        for row in mat:
            for val in row:
                f.write(f"{int(val) & 0xFFFFFFFF:08X}\n")

def save_hex_vector(filename, vec):
    """
    Save 1D int vector as HEX lines (32-bit).
    """
    with open(filename, "w") as f:
        for v in vec:
            f.write(f"{int(v) & 0xFFFFFFFF:08X}\n")


os.makedirs("fpga_export", exist_ok=True)

save_hex_matrix(os.path.join("fpga_export", "W1.hex"), W1_packed)
save_hex_matrix(os.path.join("fpga_export", "W2.hex"), W2_packed)
save_hex_vector(os.path.join("fpga_export", "TH1.hex"), TH1)
save_hex_vector(os.path.join("fpga_export", "TH2.hex"), TH2)

print("Exported FPGA files in ./fpga_export/")
print("  W1.hex  (HIDDEN x WORDS_INPUT)")
print("  W2.hex  (OUTPUT x WORDS_HIDDEN)")
print("  TH1.hex (HIDDEN thresholds)")
print("  TH2.hex (OUTPUT thresholds)")
print("All done.")

# ----------------- MNIST TESTER (drop in after your model/training) -----------------
import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

def ensure_mnist_loaded():
    """Ensure x_test and y_test are available as globals (normalized float images)."""
    global x_test, y_test
    try:
        _ = x_test, y_test
    except NameError:
        (_, _), (x_test_raw, y_test_raw) = mnist.load_data()
        x_test = x_test_raw.reshape(-1, INPUT).astype(np.float32) / 255.0
        y_test = y_test_raw
    return x_test, y_test

def load_model_from_npz(path, model):
    """Load float params stored by model.save_npz into an existing model instance."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"Saved model not found at: {path}")
    d = np.load(path)
    model.w1 = d["w1"].astype(np.float32)
    model.b1 = d["b1"].astype(np.float32)
    model.w2 = d["w2"].astype(np.float32)
    model.b2 = d["b2"].astype(np.float32)
    model.gamma1 = d["gamma1"].astype(np.float32)
    model.beta1  = d["beta1"].astype(np.float32)
    model.gamma2 = d["gamma2"].astype(np.float32)
    model.beta2  = d["beta2"].astype(np.float32)
    return model

def test_single_mnist(model=None, use_saved_if_needed=True, save_path=SAVE_PATH, show_image=True):
    """
    Ask the user for an integer index (or press Enter for random), show the 28x28 image,
    run model.forward_float() and print predicted class + top-3 probabilities.

    - model: an existing XNOR_BNN_Model instance (if None, we will create one and try to load saved params).
    - use_saved_if_needed: if True and model is None, attempt to load parameters from save_path.
    """
    x_test, y_test = ensure_mnist_loaded()

    # prepare model
    if model is None:
        if not use_saved_if_needed:
            raise ValueError("No model provided and use_saved_if_needed is False.")
        # build fresh model instance and try to load saved params
        model = XNOR_BNN_Model(INPUT, HIDDEN, OUTPUT, lr=LR)
        try:
            model = load_model_from_npz(save_path, model)
            print("Loaded saved params from", save_path)
        except Exception as e:
            print("Warning: could not load saved params:", e)
            print("Using randomly initialized model (predictions will be meaningless).")

    # ask user for an index (or random)
    prompt = f"Enter an index (0..{x_test.shape[0]-1}) or press Enter for a random MNIST test image: "
    s = input(prompt).strip()
    if s == "":
        idx = np.random.randint(0, x_test.shape[0])
    else:
        try:
            idx = int(s) % x_test.shape[0]
        except Exception:
            print("Invalid input: using a random index.")
            idx = np.random.randint(0, x_test.shape[0])

    img_flat = x_test[idx:idx+1]  # shape (1, 784)
    gt_label = int(y_test[idx])
    img_2d = (img_flat.reshape(28, 28) * 255).astype(np.uint8)

    # display image
    if show_image:
        plt.figure(figsize=(3,3))
        plt.imshow(img_2d, cmap="gray", interpolation="nearest")
        plt.axis("off")
        plt.title(f"Index: {idx}    Label: {gt_label}")
        plt.show()

    # forward pass
    probs, _ = model.forward_float(img_flat)
    probs = probs.ravel().astype(np.float32)
    pred = int(np.argmax(probs))
    # top-3
    top3_idx = np.argsort(probs)[::-1][:3]

    print(f"\nGround-truth label: {gt_label}")
    print(f"Model predicted class: {pred}")
    print("Top-3 probabilities:")
    for i in top3_idx:
        print(f"  class {i}: {probs[i]*100:.2f}%")

    return {"index": idx, "label": gt_label, "pred": pred, "probs": probs}

# ---------------- Example usages ----------------
# 1) If you are running this right after training and `model` is in memory:
#    result = test_single_mnist(model, use_saved_if_needed=False)
#
# 2) If you want to load the saved parameters from SAVE_PATH into a fresh model:
#    result = test_single_mnist(None, use_saved_if_needed=True, save_path=SAVE_PATH)
#
# 3) To repeatedly test in a small loop:
#    for _ in range(3): test_single_mnist(model)   # press Enter for random each time